namespace a_wasdk_app
{
    [default_interface]
    runtimeclass MainWindow : Microsoft.UI.Xaml.Window
    {
        MainWindow();
        Int32 MyProperty;
    }

    runtimeclass PhoneDevice : Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        PhoneDevice();
        PhoneDevice(String name);
        String DeviceName;
    }

    runtimeclass DevicesPage : Microsoft.UI.Xaml.Controls.Page, Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        DevicesPage();
        Windows.Foundation.Collections.IVector<IInspectable> Devices{ get; };
    }
}
